### ISSUE TITLE
Error with thousand separator in the field "duration" of main menu

### ISSUE THREAD

**Issue by miguelgz36** [miguelgz36/SimulatorBacterialBiofilms#58]
![imagen](https://user-images.githubusercontent.com/68168635/97788539-9a686580-1b87-11eb-8714-d40d82c1aeb5.png)

**Comment by orozcojuan1998** [comment]
Can you submit a picture of the interface in full screen mode?

**Comment by orozcojuan1998** [comment]
Solved
